/**
 * Transport crypto unit tests, including the cross-end golden vectors.
 *
 * The e2e suite (test_encryption_e2e.js) drives a live hub; this file checks the crypto layer
 * itself, which is where the four implementations (Node, Kotlin, and the two browser copies) have
 * to agree byte for byte. test/vectors/e2e-v2.json is generated by Node and asserted by
 * CryptoEngineTest.kt on Android too, so a change here that breaks the vectors breaks Android.
 *
 * Run: node --test test/
 */
const test = require('node:test');
const assert = require('node:assert');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const ROOT = path.resolve(__dirname, '..');
const PROTO = require(path.join(ROOT, 'apps/desktop/desktop_hub/crypto_protocol'));
const VECTORS = require(path.join(ROOT, 'test/vectors/e2e-v2.json'));
const SPEC = require(path.join(ROOT, 'protocol.json'));

const KEY = Buffer.from(VECTORS.keyHex, 'hex');

test('the implementation, the contract and the vectors name the same protocol', () => {
  assert.strictEqual(PROTO.PROTOCOL, SPEC.crypto.protocol);
  assert.strictEqual(VECTORS.protocol, SPEC.crypto.protocol);
});

test('key material widths match the contract', () => {
  assert.strictEqual(PROTO.KEY_LEN, SPEC.crypto.keyLenBytes);
  assert.strictEqual(PROTO.NONCE_LEN, SPEC.crypto.nonceLenBytes);
  assert.strictEqual(PROTO.TAG_LEN, SPEC.crypto.tagLenBytes);
  assert.strictEqual(VECTORS.constants.keyLen, PROTO.KEY_LEN);
  assert.strictEqual(VECTORS.constants.nonceLen, PROTO.NONCE_LEN);
  assert.strictEqual(VECTORS.constants.tagLen, PROTO.TAG_LEN);
});

test('HKDF and proof inputs are built from the contract templates', () => {
  const vars = { protocol: PROTO.PROTOCOL, sessionId: VECTORS.sessionId, pairingSecret: VECTORS.pairingSecret };
  assert.strictEqual(Buffer.from(PROTO.format('kdfSalt', vars)).toString('hex'), VECTORS.kdf.saltInputHex);
  assert.strictEqual(
    crypto.createHash('sha256').update(PROTO.format('kdfSalt', vars)).digest('hex'),
    VECTORS.kdf.saltDigestHex
  );
  assert.strictEqual(Buffer.from(PROTO.format('kdfInfo', vars)).toString('hex'), VECTORS.kdf.infoHex);
  assert.strictEqual(Buffer.from(PROTO.format('clientProof', vars)).toString('hex'), VECTORS.kdf.clientProofInputHex);
  assert.strictEqual(Buffer.from(PROTO.format('serverProof', vars)).toString('hex'), VECTORS.kdf.serverProofInputHex);
});

test('the HMAC proofs match the vectors and each other only when they should', () => {
  assert.strictEqual(PROTO.clientProof(KEY, VECTORS.sessionId).toString('hex'), VECTORS.kdf.clientProofHex);
  assert.strictEqual(PROTO.serverProof(KEY, VECTORS.sessionId).toString('hex'), VECTORS.kdf.serverProofHex);
  assert.ok(PROTO.clientProof(KEY, VECTORS.sessionId).equals(PROTO.serverProof(KEY, VECTORS.sessionId)) === false,
    'client and server proofs must not be interchangeable');
  assert.ok(PROTO.verifyClientProof(KEY, VECTORS.sessionId, VECTORS.kdf.clientProofHex));
  assert.ok(!PROTO.verifyClientProof(KEY, VECTORS.sessionId, VECTORS.kdf.serverProofHex), 'the server proof must not satisfy the client check');
});

test('verifyClientProof refuses malformed input instead of throwing', () => {
  assert.strictEqual(PROTO.verifyClientProof(KEY, VECTORS.sessionId, ''), false);
  assert.strictEqual(PROTO.verifyClientProof(KEY, VECTORS.sessionId, 'zz' + '00'.repeat(31)), false);
  assert.strictEqual(PROTO.verifyClientProof(KEY, VECTORS.sessionId, '00'.repeat(31)), false);
  assert.strictEqual(PROTO.verifyClientProof(KEY, VECTORS.sessionId, undefined), false);
});

test('every AAD in the vectors matches the contract layout', () => {
  for (const entry of VECTORS.aad) {
    const aad = PROTO.chunkAad(entry.taskId, entry.index, entry.count, entry.chunkSize);
    assert.strictEqual(aad.toString('hex'), entry.hex, `AAD differs for ${entry.taskId} ${entry.index}/${entry.count}`);
    assert.strictEqual(aad.toString('utf8'),
      `${SPEC.crypto.protocol}|chunk|${entry.taskId}|${entry.index}|${entry.count}|${entry.chunkSize}`);
  }
});

test('chunk geometry outside the agreed envelope is refused before any crypto runs', () => {
  const bad = [
    ['index equal to count', ['t', 3, 3, 64]],
    ['index past count', ['t', 4, 3, 64]],
    ['negative index', ['t', -1, 3, 64]],
    ['zero chunks', ['t', 0, 0, 64]],
    ['count above the cap', ['t', 0, SPEC.chunking.maxChunksPerTask + 1, 64]],
    ['stride above the ceiling', ['t', 0, 1, SPEC.chunking.maxSealedChunkBytes + 1]],
    ['zero stride', ['t', 0, 1, 0]],
    ['non-numeric index', ['t', 'x', 3, 64]],
    ['fractional stride', ['t', 0, 3, 64.5]]
  ];
  for (const [why, args] of bad) {
    assert.throws(() => PROTO.chunkAad(...args), new RegExp('.'), `chunkAad should refuse ${why}`);
    assert.throws(() => PROTO.encryptChunk(KEY, Buffer.alloc(16), ...args), new RegExp('.'), `encryptChunk should refuse ${why}`);
  }
});

test('format() refuses to leave a placeholder unsubstituted', () => {
  assert.throws(() => PROTO.format('chunkAad', { protocol: PROTO.PROTOCOL, taskId: 't', index: 0, count: 1 }), /chunkSize/);
  assert.throws(() => PROTO.format('nope', {}), /unknown template/);
});

test('every sealed vector decrypts to its plaintext and keeps its framing', () => {
  for (const chunk of VECTORS.chunks) {
    const sealed = Buffer.from(chunk.sealedHex, 'hex');
    const opened = PROTO.decryptChunk(KEY, sealed, chunk.taskId, chunk.index, chunk.count, chunk.chunkSize);
    assert.strictEqual(opened.toString('hex'), chunk.plaintextHex, `plaintext differs for ${chunk.taskId} ${chunk.index}`);
    assert.strictEqual(sealed.subarray(0, PROTO.NONCE_LEN).toString('hex'), chunk.nonceHex);
    assert.strictEqual(sealed.subarray(sealed.length - PROTO.TAG_LEN).toString('hex'), chunk.tagHex);
    assert.strictEqual(sealed.length - PROTO.NONCE_LEN - PROTO.TAG_LEN, chunk.ciphertextLen);
  }
});

test('every rejected vector is actually refused', () => {
  for (const entry of VECTORS.reject) {
    assert.throws(
      () => PROTO.decryptChunk(KEY, Buffer.from(entry.sealedHex, 'hex'), entry.taskId, entry.index, entry.count, entry.chunkSize),
      new RegExp('.'),
      `should have been refused: ${entry.why}`
    );
  }
});

test('sealing twice under one key never reuses a nonce', () => {
  const plaintext = Buffer.from('the same bytes, sealed twice');
  const first = PROTO.encryptChunk(KEY, plaintext, 'task_nonce', 0, 1, plaintext.length);
  const second = PROTO.encryptChunk(KEY, plaintext, 'task_nonce', 0, 1, plaintext.length);
  assert.notStrictEqual(first.subarray(0, PROTO.NONCE_LEN).toString('hex'), second.subarray(0, PROTO.NONCE_LEN).toString('hex'));
  assert.notStrictEqual(first.toString('hex'), second.toString('hex'));
});

test('a chunk from one session key does not open under another', () => {
  const other = crypto.randomBytes(PROTO.KEY_LEN);
  const sealed = PROTO.encryptChunk(KEY, Buffer.from('not for you'), 'task_key', 0, 1, 11);
  assert.throws(() => PROTO.decryptChunk(other, sealed, 'task_key', 0, 1, 11), new RegExp('.'));
});

test('session keys differ per session id and per pairing secret', () => {
  const pair = PROTO.generateKeyPair('x25519');
  const secret = PROTO.computeSharedSecret(pair.privateKey, PROTO.exportRawPublicKey(pair, 'x25519'), 'x25519');
  const base = PROTO.deriveSessionKey(secret, 'session-a', '123456');
  assert.strictEqual(base.length, PROTO.KEY_LEN);
  assert.notStrictEqual(PROTO.deriveSessionKey(secret, 'session-b', '123456').toString('hex'), base.toString('hex'));
  assert.notStrictEqual(PROTO.deriveSessionKey(secret, 'session-a', '123457').toString('hex'), base.toString('hex'));
});

test('both curves round-trip a raw public key through the SPKI prefix', () => {
  for (const curve of ['x25519', 'p-256']) {
    const pair = PROTO.generateKeyPair(curve);
    const raw = PROTO.exportRawPublicKey(pair, curve);
    assert.strictEqual(raw.length, SPEC.crypto.curves[curve].rawLenBytes, `${curve} raw length`);
    assert.strictEqual(PROTO.curveFromRawLength(raw.length), curve);
    const reimported = PROTO.importRawPublicKey(raw, curve);
    const again = PROTO.exportRawPublicKey({ publicKey: reimported }, curve);
    assert.strictEqual(again.toString('hex'), raw.toString('hex'), `${curve} survives import/export`);
  }
  assert.throws(() => PROTO.curveFromRawLength(7), new RegExp('.'));
});

test('the committed vectors are reproducible from the current code', () => {
  execFileSync(process.execPath, [path.join(ROOT, 'scripts/gen-vectors.js'), '--check'], { cwd: ROOT, stdio: 'pipe' });
});
