package com.safedrop.mobile.core.crypto

/* GENERATED by scripts/protocol.js gen from protocol.json - do not edit by hand. */
/* Change the contract in protocol.json, then run: node scripts/protocol.js gen */

/** Cross-end constants. The hub reads the same values from protocol.gen.js. */
object ProtocolConst {
    const val PROTOCOL: String = "safedrop-e2e-v2"
    const val KEY_LEN_BYTES = 32
    const val NONCE_LEN_BYTES = 12
    const val TAG_LEN_BYTES = 16
    const val TAG_LEN_BITS = 128
    const val X25519_RAW_LEN_BYTES = 32

    const val TPL_KDF_SALT: String = "{protocol}|salt|{sessionId}"
    const val TPL_KDF_INFO: String = "{protocol}|key|{pairingSecret}"
    const val TPL_CLIENT_PROOF: String = "{protocol}|verify|{sessionId}"
    const val TPL_SERVER_PROOF: String = "{protocol}|server|{sessionId}"
    const val TPL_CHUNK_AAD: String = "{protocol}|chunk|{taskId}|{index}|{count}|{chunkSize}"

    /** SubjectPublicKeyInfo prefix for a raw X25519 key; the same bytes crypto_protocol.js uses. */
    val X25519_SPKI_PREFIX: ByteArray = byteArrayOf(0x30.toByte(), 0x2a.toByte(), 0x30.toByte(), 0x05.toByte(), 0x06.toByte(), 0x03.toByte(), 0x2b.toByte(), 0x65.toByte(), 0x6e.toByte(), 0x03.toByte(), 0x21.toByte(), 0x00.toByte())

    object Pairing {
        const val PIN_DIGITS = 6
        const val PIN_MIN = 100000
        const val PIN_MAX_EXCLUSIVE = 1000000
        const val TOKEN_HEX_CHARS = 12
        const val GRACE_MS = 60000L
        const val GRACE_GENERATIONS = 3
        const val MAX_FAILURES = 8
        const val FAILURE_WINDOW_MS = 300000L
        const val BLOCK_MS = 300000L
    }

    object Session {
        const val IDLE_TTL_MS = 600000L
        const val MAX_TTL_MS = 43200000L
    }

    object Discovery {
        const val UDP_PORT = 8890
        const val BEACON_INTERVAL_MS = 3000L
    }

    object Chunking {
        const val SEALED_OVERHEAD_BYTES = 28
        const val MAX_SEALED_CHUNK_BYTES = 67108864
        const val MAX_CHUNKS_PER_TASK = 1000000
        /** This device's own upload slice size; the value is per-end tuning, see protocol.json. */
        const val PREFERRED_CHUNK_SIZE_BYTES = 1048576
    }

    object Headers {
        const val TASKID: String = "X-Task-Id"
        const val FILENAME: String = "X-File-Name"
        const val FILESIZE: String = "X-File-Size"
        const val CHUNKINDEX: String = "X-Chunk-Index"
        const val CHUNKCOUNT: String = "X-Chunk-Count"
        const val CHUNKSIZE: String = "X-Chunk-Size"
        const val ENCRYPTED: String = "X-Encrypted"
        const val COMPRESSED: String = "X-Compressed"
        const val ORIGINALSIZE: String = "X-Original-Size"
        const val SESSIONID: String = "X-Session-Id"
        const val TARGETIP: String = "X-Target-Ip"
        const val TARGETPORT: String = "X-Target-Port"
        const val TARGETNAME: String = "X-Target-Name"
        const val TARGETSESSIONID: String = "X-Target-Session-Id"
    }
}
