/* GENERATED by scripts/protocol.js gen from protocol.json - do not edit by hand. */
/* Change the contract in protocol.json, then run: node scripts/protocol.js gen */
'use strict';

module.exports = {
  PROTOCOL: "safedrop-e2e-v2",
  KEY_LEN: 32,
  NONCE_LEN: 12,
  TAG_LEN: 16,
  TAG_BITS: 128,
  HKDF_HASH: "sha-256",
  SEALED_OVERHEAD: 28,
  MAX_SEALED_CHUNK: 67108864,
  MAX_CHUNKS_PER_TASK: 1000000,
  CURVES: {
    "x25519": { node: "x25519", rawLen: 32, spkiPrefix: Buffer.from('302a300506032b656e032100', 'hex') },
    "p-256": { node: "prime256v1", rawLen: 65, spkiPrefix: Buffer.from('3059301306072a8648ce3d020106082a8648ce3d030107034200', 'hex') }
  },
  TEMPLATES: {
    "kdfSalt": "{protocol}|salt|{sessionId}",
    "kdfInfo": "{protocol}|key|{pairingSecret}",
    "clientProof": "{protocol}|verify|{sessionId}",
    "serverProof": "{protocol}|server|{sessionId}",
    "chunkAad": "{protocol}|chunk|{taskId}|{index}|{count}|{chunkSize}"
  },
  PAIRING: {
    PIN_DIGITS: 6,
    PIN_MIN: 100000,
    PIN_MAX_EXCLUSIVE: 1000000,
    TOKEN_BYTES: 6,
    GRACE_MS: 60000,
    GRACE_GENERATIONS: 3,
    MAX_FAILURES: 8,
    FAILURE_WINDOW_MS: 300000,
    BLOCK_MS: 300000
  },
  SESSION: {
    IDLE_TTL_MS: 600000,
    MAX_TTL_MS: 43200000
  },
  DISCOVERY: {
    UDP_PORT: 8890,
    BEACON_INTERVAL_MS: 3000
  },
  TRANSPORT: {
    HUB_PORT: 8899,
    TLS_PORT_DELTA: 1
  },
  HEADERS: {
    "taskId": "X-Task-Id",
    "fileName": "X-File-Name",
    "fileSize": "X-File-Size",
    "chunkIndex": "X-Chunk-Index",
    "chunkCount": "X-Chunk-Count",
    "chunkSize": "X-Chunk-Size",
    "encrypted": "X-Encrypted",
    "compressed": "X-Compressed",
    "originalSize": "X-Original-Size",
    "sessionId": "X-Session-Id",
    "targetIp": "X-Target-Ip",
    "targetPort": "X-Target-Port",
    "targetName": "X-Target-Name",
    "targetSessionId": "X-Target-Session-Id"
  }
};
