#!/usr/bin/env node
'use strict';

/**
 * protocol.json is the contract; this script turns it into the two files that must not drift by
 * hand, and then checks the copies that cannot be generated (the browser pages have to stay
 * self-contained, so their literals are asserted instead of produced).
 *
 *   node scripts/protocol.js gen     write the generated files
 *   node scripts/protocol.js check   fail if anything disagrees with protocol.json
 *
 * Why generation for Node and Kotlin but assertion for the browser: app.js and portal.html are
 * loaded as plain scripts from disk (portal.html is even copied verbatim into the APK assets so a
 * phone can serve it without a build step), so a generated import there would mean a new served
 * file on three paths. Asserting the literals keeps one contract and no packaging change.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SPEC_FILE = 'protocol.json';

const SPEC = JSON.parse(fs.readFileSync(path.join(ROOT, SPEC_FILE), 'utf8'));
const C = SPEC.crypto;
const CH = SPEC.chunking;
const P = SPEC.pairing;
const S = SPEC.session;
const D = SPEC.discovery;
const T = SPEC.transport;

const TARGETS = {
  node: 'apps/desktop/desktop_hub/protocol.gen.js',
  kotlin: 'apps/android/com/app/src/main/java/com/safedrop/mobile/core/crypto/ProtocolConst.kt'
};

/** Browser files that carry hand-written copies of the contract, and how they spell it. */
const BROWSER_COPIES = [
  'apps/desktop/desktop_hub/public/app.js',
  'apps/desktop/desktop_hub/public/portal.html',
  'apps/android/com/app/src/main/assets/portal.html'
];

/** The one implementation that reads the headers rather than sending them. */
const HEADER_USER = 'apps/desktop/desktop_hub/server.js';

/** Documents that state which wire protocol is in force, so they cannot drift from the code. */
const DOC_FILES = ['README.md', 'apps/android/README.md'];

const BROWSER_VARS = {
  protocol: '${PROTOCOL}',
  sessionId: '${sessionId}',
  pairingSecret: '${pairingSecret}',
  taskId: '${taskId}',
  index: '${index}',
  count: '${count}',
  chunkSize: '${chunkSize}'
};

const BANNER_NODE = [
  '/* GENERATED by scripts/protocol.js gen from protocol.json - do not edit by hand. */',
  '/* Change the contract in protocol.json, then run: node scripts/protocol.js gen */',
  "'use strict';",
  ''
].join('\n');

function jsNumber(n) {
  return String(n);
}

function nodeSource() {
  const curves = Object.entries(C.curves)
    .map(([name, spec]) => `    ${JSON.stringify(name)}: { node: ${JSON.stringify(spec.opensslName)}, rawLen: ${jsNumber(spec.rawLenBytes)}, spkiPrefix: Buffer.from('${spec.spkiPrefixHex}', 'hex') }`)
    .join(',\n');
  const templates = Object.entries(C.templates)
    .map(([name, tpl]) => `    ${JSON.stringify(name)}: ${JSON.stringify(tpl)}`)
    .join(',\n');
  const headers = Object.entries(T.headers)
    .map(([name, header]) => `    ${JSON.stringify(name)}: ${JSON.stringify(header)}`)
    .join(',\n');

  return `${BANNER_NODE}
module.exports = {
  PROTOCOL: ${JSON.stringify(C.protocol)},
  KEY_LEN: ${jsNumber(C.keyLenBytes)},
  NONCE_LEN: ${jsNumber(C.nonceLenBytes)},
  TAG_LEN: ${jsNumber(C.tagLenBytes)},
  TAG_BITS: ${jsNumber(C.tagLenBits)},
  HKDF_HASH: ${JSON.stringify(C.hkdfHash.toLowerCase())},
  SEALED_OVERHEAD: ${jsNumber(CH.sealedOverheadBytes)},
  MAX_SEALED_CHUNK: ${jsNumber(CH.maxSealedChunkBytes)},
  MAX_CHUNKS_PER_TASK: ${jsNumber(CH.maxChunksPerTask)},
  CURVES: {
${curves}
  },
  TEMPLATES: {
${templates}
  },
  PAIRING: {
    PIN_DIGITS: ${jsNumber(P.pinDigits)},
    PIN_MIN: ${jsNumber(P.pinMin)},
    PIN_MAX_EXCLUSIVE: ${jsNumber(P.pinMaxExclusive)},
    TOKEN_BYTES: ${jsNumber(P.tokenHexBytes)},
    GRACE_MS: ${jsNumber(P.graceMs)},
    GRACE_GENERATIONS: ${jsNumber(P.graceGenerations)},
    MAX_FAILURES: ${jsNumber(P.maxFailures)},
    FAILURE_WINDOW_MS: ${jsNumber(P.failureWindowMs)},
    BLOCK_MS: ${jsNumber(P.blockMs)}
  },
  SESSION: {
    IDLE_TTL_MS: ${jsNumber(S.idleTtlMs)},
    MAX_TTL_MS: ${jsNumber(S.maxTtlMs)}
  },
  DISCOVERY: {
    UDP_PORT: ${jsNumber(D.udpPort)},
    BEACON_INTERVAL_MS: ${jsNumber(D.beaconIntervalMs)}
  },
  TRANSPORT: {
    HUB_PORT: ${jsNumber(T.hubPort)},
    TLS_PORT_DELTA: ${jsNumber(T.hubTlsPortDelta)}
  },
  HEADERS: {
${headers}
  }
};
`;
}

function kotlinNumber(n) {
  return String(n);
}

function kotlinSource() {
  const spki = JSON.parse(fs.readFileSync(path.join(ROOT, SPEC_FILE), 'utf8')).crypto.curves.x25519.spkiPrefixHex;
  const bytes = (spki.match(/../g) || []).map((hex) => `0x${hex}.toByte()`).join(', ');
  return `package com.safedrop.mobile.core.crypto

/* GENERATED by scripts/protocol.js gen from protocol.json - do not edit by hand. */
/* Change the contract in protocol.json, then run: node scripts/protocol.js gen */

/** Cross-end constants. The hub reads the same values from protocol.gen.js. */
object ProtocolConst {
    const val PROTOCOL: String = "${C.protocol}"
    const val KEY_LEN_BYTES = ${kotlinNumber(C.keyLenBytes)}
    const val NONCE_LEN_BYTES = ${kotlinNumber(C.nonceLenBytes)}
    const val TAG_LEN_BYTES = ${kotlinNumber(C.tagLenBytes)}
    const val TAG_LEN_BITS = ${kotlinNumber(C.tagLenBits)}
    const val X25519_RAW_LEN_BYTES = ${kotlinNumber(C.curves.x25519.rawLenBytes)}

    const val TPL_KDF_SALT: String = "${C.templates.kdfSalt}"
    const val TPL_KDF_INFO: String = "${C.templates.kdfInfo}"
    const val TPL_CLIENT_PROOF: String = "${C.templates.clientProof}"
    const val TPL_SERVER_PROOF: String = "${C.templates.serverProof}"
    const val TPL_CHUNK_AAD: String = "${C.templates.chunkAad}"

    /** SubjectPublicKeyInfo prefix for a raw X25519 key; the same bytes crypto_protocol.js uses. */
    val X25519_SPKI_PREFIX: ByteArray = byteArrayOf(${bytes})

    object Pairing {
        const val PIN_DIGITS = ${kotlinNumber(P.pinDigits)}
        const val PIN_MIN = ${kotlinNumber(P.pinMin)}
        const val PIN_MAX_EXCLUSIVE = ${kotlinNumber(P.pinMaxExclusive)}
        const val TOKEN_HEX_CHARS = ${kotlinNumber(P.tokenHexBytes * 2)}
        const val GRACE_MS = ${kotlinNumber(P.graceMs)}L
        const val GRACE_GENERATIONS = ${kotlinNumber(P.graceGenerations)}
        const val MAX_FAILURES = ${kotlinNumber(P.maxFailures)}
        const val FAILURE_WINDOW_MS = ${kotlinNumber(P.failureWindowMs)}L
        const val BLOCK_MS = ${kotlinNumber(P.blockMs)}L
    }

    object Session {
        const val IDLE_TTL_MS = ${kotlinNumber(S.idleTtlMs)}L
        const val MAX_TTL_MS = ${kotlinNumber(S.maxTtlMs)}L
    }

    object Discovery {
        const val UDP_PORT = ${kotlinNumber(D.udpPort)}
        const val BEACON_INTERVAL_MS = ${kotlinNumber(D.beaconIntervalMs)}L
    }

    object Chunking {
        const val SEALED_OVERHEAD_BYTES = ${kotlinNumber(CH.sealedOverheadBytes)}
        const val MAX_SEALED_CHUNK_BYTES = ${kotlinNumber(CH.maxSealedChunkBytes)}
        const val MAX_CHUNKS_PER_TASK = ${kotlinNumber(CH.maxChunksPerTask)}
        /** This device's own upload slice size; the value is per-end tuning, see protocol.json. */
        const val PREFERRED_CHUNK_SIZE_BYTES = ${kotlinNumber(CH.preferredChunkSizeBytes.android)}
    }

    object Headers {
${Object.entries(T.headers).map(([name, header]) => `        const val ${name.toUpperCase().replace(/-/g, '_')}: String = "${header}"`).join('\n')}
    }
}
`;
}

function generate() {
  const written = [];
  for (const [kind, rel] of Object.entries(TARGETS)) {
    const source = kind === 'node' ? nodeSource() : kotlinSource();
    const abs = path.join(ROOT, rel);
    fs.mkdirSync(path.dirname(abs), { recursive: true });
    const existing = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
    if (existing !== source) fs.writeFileSync(abs, source, 'utf8');
    written.push(rel);
  }
  return written;
}

/** Where each browser copy states its upload slice size, and which tuning key it must match. */
const CHUNK_LITERAL_SITES = {
  'apps/desktop/desktop_hub/public/app.js': 'desktop',
  'apps/desktop/desktop_hub/public/portal.html': 'portal',
  'apps/android/com/app/src/main/assets/portal.html': 'portal'
};

function chunkLiteral(bytes) {
  const mb = bytes / (1024 * 1024);
  return mb === 1 ? '1024 * 1024' : `${mb} * 1024 * 1024`;
}

const failures = [];
function fail(msg) {
  failures.push(msg);
}

function normalize(text) {
  return text.replace(/\r\n/g, '\n');
}

function checkGenerated() {
  for (const [kind, rel] of Object.entries(TARGETS)) {
    const abs = path.join(ROOT, rel);
    if (!fs.existsSync(abs)) {
      fail(`${rel} is missing - run: node scripts/protocol.js gen`);
      continue;
    }
    const want = normalize(kind === 'node' ? nodeSource() : kotlinSource());
    const have = normalize(fs.readFileSync(abs, 'utf8'));
    if (want !== have) fail(`${rel} disagrees with ${SPEC_FILE} - run: node scripts/protocol.js gen`);
  }
}

/** Turn a spec template into the exact text a browser script must contain. */
function browserLiteral(template) {
  let out = template;
  for (const [placeholder, spelling] of Object.entries(BROWSER_VARS)) {
    out = out.split(`{${placeholder}}`).join(spelling);
  }
  return out;
}

function checkBrowserCopies() {
  for (const rel of BROWSER_COPIES) {
    const abs = path.join(ROOT, rel);
    if (!fs.existsSync(abs)) {
      fail(`${rel} is missing`);
      continue;
    }
    const src = fs.readFileSync(abs, 'utf8');
    if (!src.includes(`PROTOCOL = '${C.protocol}'`)) {
      fail(`${rel}: PROTOCOL literal is not '${C.protocol}'`);
    }
    const tuning = CHUNK_LITERAL_SITES[rel];
    if (tuning) {
      const want = chunkLiteral(CH.preferredChunkSizeBytes[tuning]);
      if (!src.includes(want)) {
        fail(`${rel}: the upload slice size is no longer ${want}, which ${SPEC_FILE} assigns to "${tuning}"`);
      }
    }
    for (const [name, template] of Object.entries(C.templates)) {
      if (!src.includes(browserLiteral(template))) {
        fail(`${rel}: ${name} template does not match ${SPEC_FILE} (expected \`${browserLiteral(template)}\`)`);
      }
    }
  }
}

function checkDuplicatedPortal() {
  const desktop = path.join(ROOT, 'apps/desktop/desktop_hub/public/portal.html');
  const apk = path.join(ROOT, 'apps/android/com/app/src/main/assets/portal.html');
  if (fs.readFileSync(desktop, 'utf8') !== fs.readFileSync(apk, 'utf8')) {
    fail('public/portal.html and the APK asset copy differ; the phone serves a different portal than the desktop');
  }
}

/** The README is the compatibility statement users read; it has to name the protocol in force. */
function checkDocs() {
  for (const rel of DOC_FILES) {
    const abs = path.join(ROOT, rel);
    if (!fs.existsSync(abs)) {
      fail(`${rel} is missing`);
      continue;
    }
    if (!fs.readFileSync(abs, 'utf8').includes(C.protocol)) {
      fail(`${rel} never mentions ${C.protocol}, the wire protocol this code actually speaks`);
    }
  }
}

/**
 * Header names are the other half of the contract, and the files that use them spell them out as
 * literals. Rather than assume each file needs every header - the browser pages send a subset and
 * the hub parses a different one - scan what each file actually writes and require every custom
 * name in it to exist in the contract. Rename a header there and the code that still uses the old
 * spelling is named immediately, which is the drift that leaves one end silently deaf.
 */
function checkHeaderNames() {
  const known = new Set(Object.values(T.headers).map((name) => name.toLowerCase()));
  for (const rel of [HEADER_USER, ...BROWSER_COPIES]) {
    const abs = path.join(ROOT, rel);
    if (!fs.existsSync(abs)) continue;
    const src = fs.readFileSync(abs, 'utf8');
    for (const match of src.matchAll(/['"]([xX]-[a-zA-Z0-9][a-zA-Z0-9-]*)['"]/g)) {
      if (!known.has(match[1].toLowerCase())) {
        fail(`${rel}: uses "${match[1]}" as a header, which ${SPEC_FILE} does not define`);
      }
    }
  }
}

function check() {
  checkGenerated();
  checkBrowserCopies();
  checkDuplicatedPortal();
  checkHeaderNames();
  checkDocs();
  if (failures.length) {
    console.error(`protocol check FAILED (${failures.length}):`);
    for (const f of failures) console.error(`  - ${f}`);
    process.exit(1);
  }
  const files = [...Object.values(TARGETS), ...BROWSER_COPIES, HEADER_USER, ...DOC_FILES].length;
  console.log(`protocol check passed: ${C.protocol}, ${Object.keys(C.templates).length} templates, ${files} files agree with ${SPEC_FILE}`);
}

const mode = process.argv[2];
if (mode === 'gen') {
  for (const rel of generate()) console.log(`wrote ${rel}`);
} else if (mode === 'check') {
  check();
} else {
  console.error('usage: node scripts/protocol.js <gen|check>');
  process.exit(2);
}
